### ISSUE TITLE
創刊號內容，懂？

### ISSUE THREAD

**Issue by venetiachou** [the-useless-zine/PinkyPenguin#1]

**Comment by venetiachou** [comment]
提議文末來個隨便亂問的專欄，一個問題，各自表述
像是
問：奇怪的生活習慣？
蝦妹：每天吃壯陽藥功效的瑪卡粉（不開玩笑，治療荷爾蒙痘痘超有效，用英文查就懂，懂？）

來點互動，懂？

**Comment by bugtender** [comment]
懂

請問創刊號什麼時候？

**Comment by venetiachou** [comment]
> 懂
> 
> 請問創刊號什麼時候？

這就有趣了，不是應該先搜集名單嗎

**Comment by bugtender** [comment]
那就七月一號好了

**Comment by venetiachou** [comment]
那該開始搜集名單了，我要來寫一篇 Medium 文章告訴大家這個好消息。
