### ISSUE TITLE
Issue #6

### ISSUE THREAD

**Issue by bugtender** [the-useless-zine/PinkyPenguin#10]
我心中沒有一絲一毫的喜悅和歡樂，只感到無比沉重的壓力。

@venetiachou 你有找到主編了嗎？

**Comment by venetiachou** [comment]
生活就像是瘋狂的過山車，前一秒你感覺很好，下一秒你會感到孤獨和絕望，看不到希望，生活不是關於情緒，不是關於你每分每秒的感覺，而是你對自己生活的看法，以及你是否為自己的身份感到自豪。

有，但他本人沒有 GitHub 帳號，你登進去 Curated 應該會看到他有正在編纂。
只是命運的齒輪出了點差錯，他突然忙著拔他那顆平躺靠近神經的智齒，不確定是否仍有餘力。
我星期五會再善意詢問，不行的話，就交給你囉。

你就是備胎。

**Comment by venetiachou** [comment]
哇靠原來那是國 fish 的話語啊

**Comment by bugtender** [comment]
無所謂，反正我這輩子都是備胎。
