### ISSUE TITLE
Issue 10 來點特別的怎麼樣？

### ISSUE THREAD

**Issue by venetiachou** [the-useless-zine/PinkyPenguin#12]
雖然大概還要有兩個月的時間（汗）
但總之就先丟出來問一下，來點特別的，你覺得要什麼？

請踴躍拋出可行性高，不唬爛的 idea。

**Comment by bugtender** [comment]
ㄜ，實體書籍？

**Comment by venetiachou** [comment]
你可能沒有看清楚，沒關係，讓我再說一次。
**請踴躍拋出可行性高，不唬爛的 idea**
我們不需要再一本小冊子了

**Comment by bugtender** [comment]
ㄜ，Podcast  版？

**Comment by venetiachou** [comment]
？？？
我們不需要再來一個 podcast 了。
難道不能來點簡單有個性一點的嗎？
這些都太平庸無奇了。

**Comment by bugtender** [comment]
ㄜ，抽獎？

**Comment by bugtender** [comment]
抱歉手抖了一下不小心按到

**Comment by venetiachou** [comment]
是要抽什麼啦，抽你從英國寄明信片給讀者膩？

**Comment by bugtender** [comment]
ㄜ，休刊一次？

**Comment by venetiachou** [comment]
欸幹，我覺得第 10 期休刊這提議不錯。

**Comment by venetiachou** [comment]
再來提一個：我 Q 我 A 的 section
- 為什麼 GitHub 名稱叫 PinkyPenguin？
- 為什麼從來沒看過拉麵系網美發文？
- 為什麼大李冗浩還沒找到工作？

**Comment by bugtender** [comment]
這不是什麼 youtuber 十萬訂閱的橋段嗎🤔

**Comment by venetiachou** [comment]
好，那就休刊 🐤

**Comment by bugtender** [comment]
我覺得可以先在 Instagram 開啓現動問答

**Comment by venetiachou** [comment]
限動啦幹

**Comment by bugtender** [comment]
@venetiachou Do you have any idea about this? 
And sorry I don't have Traditional Chinese Input on my work laptop 😖.

btw, I saw you publish a book for your flower shop on Instagram. Are you familiar with paper zine now? Maybe it's `可行性高，不唬爛的 idea` to you with issue 10.

**Comment by gaoryrt** [comment]
两个两周已经过去了，说好的第十期在哪里

**Comment by venetiachou** [comment]
由我處理，明後天會加班，應該有辦法做（？）

**Comment by bugtender** [comment]
Lovely👍
