### ISSUE TITLE
Issue #4

### ISSUE THREAD

**Issue by bugtender** [the-useless-zine/PinkyPenguin#7]
台灣安全，人民有錢！
莫忘世上苦人多！

#唯真不破

**Comment by bugtender** [comment]
啊我好像太早發了，不過沒關係，水退得快就行。

**Comment by venetiachou** [comment]
？？？
下一期要什麼主題啊
煩惱，我們接收到一個退訂，我好傷心。

**Comment by bugtender** [comment]
下一期是我嗎？還是有其他人想要嘗試？

**Comment by jiajhenbee** [comment]
是說抱歉我晚上來留言了！不意外的話第四期應該會由我擔當（？！）

**Comment by jiajhenbee** [comment]
> ？？？
> 下一期要什麼主題啊
> 煩惱，我們接收到一個退訂，我好傷心。

主題非常隨性就是分享日本有關的日常 XD

**Comment by jiajhenbee** [comment]
@venetiachou @bugtender 是說我還是不太了解要怎麼發內容，想請教兩位～

**Comment by bugtender** [comment]
issue 4 因為我昨天有先拉好草稿，所以在 Draft Issues 選擇 issue4 之後就可以開始新增連結
然後加上開頭跟結尾應該就沒問題了～
@venetiachou

**Comment by jiajhenbee** [comment]
@bugtender @venetiachou 那個很抱歉 ，我試著再New issue 和 Issue tab 裡找 Draft Issues，怎麼都找不到 Draft Issues，可以提示我在哪裡嗎？

**Comment by bugtender** [comment]
<img width="854" alt="Screen Shot 2019-08-11 at 10 28 14 AM" src="https://user-images.githubusercontent.com/5573816/62832201-c4e89e80-bc22-11e9-9632-4648e99e4ec2.png">

下期 Issue 4 有寫著 `next` 了，點進去 issue4 就可以開始！

**Comment by jiajhenbee** [comment]
原來要用 Curated 編輯，不過我好像沒有被邀請至 Curated 裡 (?!)

**Comment by bugtender** [comment]
抱歉我的疏失，請接 twitter 私訊謝謝

**Comment by venetiachou** [comment]
所以解決惹喔？！！

**Comment by jiajhenbee** [comment]
@bugtender @venetiachou 我已順利將連結放上囉，謝謝兩位的協助。另外會需要有人幫我 review 一下內容以確認一下明天發刊我沒有低級失誤 XD

**Comment by bugtender** [comment]
讚讚！我剛剛有看了一下，修了一點 bug

記得想一個廢話感十足的 title 跟 summary 喔！

**Comment by jiajhenbee** [comment]
好，謝謝！Title 跟 Summary 我盡量 XD

**Comment by jiajhenbee** [comment]
@venetiachou @bugtender 
謝謝兩位的邀請，我已順利看到自己發的文章囉，非常有趣的一個編輯經驗哈哈 🙇‍♀️
接下來還有需要我效力的部分也不吝讓我知道！
